# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
version: '3.7'

services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.8.1
    hostname: wazuh.manager
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514"
      - "55000:55000"
    environment:
      - INDEXER_URL
      - INDEXER_USERNAME
      - INDEXER_PASSWORD
      - FILEBEAT_SSL_VERIFICATION_MODE
      - SSL_CERTIFICATE_AUTHORITIES
      - SSL_CERTIFICATE
      - SSL_KEY
      - API_USERNAME
      - API_PASSWORD
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - ./config/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - ./config/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf

  wazuh.indexer:
    image: wazuh/wazuh-indexer:4.8.1
    hostname: wazuh.indexer
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    environment:
      - JAVA_HOME
      - OPENSEARCH_JAVA_OPTS
      - bootstrap.memory_lock
      - NODE_NAME
      - CLUSTER_INITIAL_MASTER_NODES
      - CLUSTER_NAME
      - PATH_DATA
      - PATH_LOGS
      - HTTP_PORT
      - TRANSPORT_TCP_PORT
      - COMPATIBILITY_OVERRIDE_MAIN_RESPONSE_VERSION
      - PLUGINS_SECURITY_SSL_HTTP_PEMCERT_FILEPATH
      - PLUGINS_SECURITY_SSL_HTTP_PEMKEY_FILEPATH
      - PLUGINS_SECURITY_SSL_HTTP_PEMTRUSTEDCAS_FILEPATH
      - PLUGINS_SECURITY_SSL_TRANSPORT_PEMCERT_FILEPATH
      - PLUGINS_SECURITY_SSL_TRANSPORT_PEMKEY_FILEPATH
      - PLUGINS_SECURITY_SSL_TRANSPORT_PEMTRUSTEDCAS_FILEPATH
      - PLUGINS_SECURITY_SSL_HTTP_ENABLED
      - PLUGINS_SECURITY_SSL_TRANSPORT_ENFORCE_HOSTNAME_VERIFICATION
      - PLUGINS_SECURITY_SSL_TRANSPORT_RESOLVE_HOSTNAME
      - PLUGINS_SECURITY_AUTHCZ_ADMIN_DN
      - PLUGINS_SECURITY_CHECK_SNAPSHOT_RESTORE_WRITE_PRIVILEGES
      - PLUGINS_SECURITY_ENABLE_SNAPSHOT_RESTORE_PRIVILEGE
      - PLUGINS_SECURITY_NODES_DN
      - PLUGINS_SECURITY_RESTAPI_ROLES_ENABLED
      - PLUGINS_SECURITY_SYSTEM_INDICES_ENABLED
      - PLUGINS_SECURITY_SYSTEM_INDICES_INDICES
      - PLUGINS_SECURITY_ALLOW_DEFAULT_INIT_SECURITYINDEX
      - CLUSTER_ROUTING_ALLOCATION_DISK_THRESHOLD_ENABLED
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      #  if you need mount a custom opensearch.yml, uncomment the next line and delete the environment variables
      # - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml

  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:4.8.1
    hostname: wazuh.dashboard
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 443
    environment:
      - WAZUH_API_URL
      - DASHBOARD_USERNAME
      - DASHBOARD_PASSWORD
      - API_USERNAME
      - API_PASSWORD
      - SERVER_HOST
      - SERVER_PORT
      - OPENSEARCH_HOSTS
      - OPENSEARCH_SSL_VERIFICATIONMODE
      - OPENSEARCH_REQUESTHEADERSALLOWLIST
      - OPENSEARCH_SECURITY_MULTITENANCY_ENABLED
      - SERVER_SSL_ENABLED
      - OPENSEARCH_SECURITY_READONLY_MODE_ROLES
      - SERVER_SSL_KEY
      - SERVER_SSL_CERTIFICATE
      - OPENSEARCH_SSL_CERTIFICATEAUTHORITIES
      - UISETTINGS_OVERRIDES_DEFAULTROUTE
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/wazuh.yml:/wazuh-config-mount/data/wazuh/config/wazuh.yml
      #  if you need mount a custom opensearch-dashboards.yml, uncomment the next line and delete the environment variables
      # - ./config/wazuh_dashboard/opensearch_dashboards.yml:/wazuh-config-mount/config/opensearch_dashboards.yml
    depends_on:
      - wazuh.indexer
      
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:
  wazuh-dashboard-config:
  wazuh-dashboard-custom:
